### ISSUE TITLE
Education Level (to be changed to Audience Level) versus Required Credential Types and Degree Requirements

### ISSUE THREAD

**Issue by bobgsheets** [CredentialTransparencyInitiative/vocabularies#103]
What is Education Level?  Is it consistently tied to degree type or credential requirements or something else?   When used with certificate or certification, it is used in various ways.
For example, Advanced Multimedia Development Certificate at University of Phoenix says Associate and Bachelors but required high school diploma or equivalent and is not clear about whether you have to be in a degree program to get the certificate.
For example, Gateway Community & Technical College--Associate of Applied Science Degree in Advanced Manufacturing Technician says associates as education level which is the level of degree awarded.

**Comment by jkitchensSIUC** [comment]
The Education Level is consistently tied to the level at which a credential and, thereby the related learning opportunity or assessment is targeted. The University of Phoenix may be correct because they offer associates and bachelors.  The certificate could be for both level.   This is very different from the condition that requires a person to have a high school diploma or equivalent to enroll in their programs.  See the definition of Education Level here http://credreg.net/page/propertiesviewer#educationLevel.  If we need to change it, please provide updated definition. 

It is correct that the Associate of Applied Science Degree in Advanced Manufacturing Technician is at the Associate Degree level.  It's redundant but this is relevant to all non-degree credentials.

**Comment by bobgsheets** [comment]
Please put on team meeting agenda for discussion.  Still not clear what you
mean by targeted and how you determine that from data they provide. Is a
certificate or certification targeted at a degree level?  Need examples of
where this is asserted.

**Comment by stuartasutton** [comment]
@bobgsheets, first, I'd emphasize that not all properties are applicable in all situations. This is one of them. 

E.g., when I create a class, I have a target education level of the audience in mind. It guides the assumptions I make about what they know, how deeply they are likely to know it, how I have to talk, their level if life experience, what I can effectively say etc. I can teach Semantic Metadata at the the high school level and it will have different outcomes and will be approached differently than if it was for undergraduate or graduate level students. This has nothing to do with requiring the audience to actually have attained any specific level. 

There are likely credentials (apprentice plumber?) that have no education level in the sense meant here, no level of assumed education on the part the audience (i.e., persons seeking it).

**Comment by bobgsheets** [comment]
In exploring this further, my question is more about:

1. It seems that most credentials specific their target education level in
terms of requirements (our requirements profile) in the form of required
credential and other requirements (e.g., passed other prerequisites in core
curriculum, work experience, passed entrance exam in reading and math).
This would be their specification of assumed education in the form of
previous credentials, work experience and direct assessment.

2. I am not aware of another credential that specifies a target education
level in addition to what is in their requirements and how they would
specify that if they do.

Again, I am looking at the websites of each pilot partner to really kick
the tires on CTDL and its implementation and this is the one that keeps
coming up in my mind.

**Comment by stuartasutton** [comment]
Bob, educaitonLevel is a property of ctdl:ConditionProfile which is only triggered by the required, recommended etc. properties. E.g.,

Credential==recommends==>ConditionProfile
ConditionProfile==educationLevel==>Bachelor

**Comment by bobgsheets** [comment]
Stuart notice jeanne's first response on education level as target of
credential and I am not sure how that relates to condition profile since it
is level that will be attained through credential and not required or
recommended for attaining that credential.  Maybe we can use example today
so I better understand.

**Comment by bobgsheets** [comment]
Hope we can review today.  Here is how I am still thinking (and maybe wrong)

1. Assumed to have should be reflected in condition profile--required or recommended.  This is where I am assuming people have some level of attainment.

2. Targeted to (credential or learning opportunity) should be reflected in type of credential (degree level) and not be applicable to certificates or certifications.  

3.  Could not find any other applications in notes above.

**Comment by siuc-nate** [comment]
As far as I can tell, Bob is correct - however its use under item 2 in the list above may not be very intuitive in terms of educational credentials: Recent discussions have shown (correct me if I'm wrong, Stuart) that a bachelor's degree Credential would have a bachelor's degree education level, not because it is targeted to people who have bachelor's degrees, but rather, because it is targeted to people who are at the bachelor's degree level (i.e., those who have completed the associated bachelor's degree program).  

The program itself would have an educationLevel of "associate" in most cases (ignoring for a moment that learning opportunity does not have an educationLevel property), because it is the program - not the credential - that is intended for an associate-level audience.  The program then trains that audience up to the bachelor's level, at which point they are "prepared" to receive the associated Credential. It's not intuitive but when you break it down like that, I can see how it makes sense.

In other words, it's another instance of the problem of separating the Credential from the thing that you do to get the credential - a problem we have run into many times in many ways. Most descriptions of degrees tend to merge the credential in with the degree program, just as many descriptions of certificates/certifications tend to conflate the description of the certificate with the assessment that is required to earn it.

At this point I'm not sure the property on Credential is worth keeping - every time it comes up, it seems like none of us are ever quite on the same page about it.  Perhaps there's a clearer, less confusing, more intuitive way to communicate what we're trying to do with it?

Its use under ConditionProfile as requirements is simple enough: 
Credential -> requires -> associate's degree

Would just using the "recommends" property be sufficient?:
Credential -> recommends -> assoicate's degree

Then you could have a credential with this kind of information:
Credential -> requires -> bachelor's degree program
Credential -> recommends -> associate's degree

Though arguably that recommendation might technically belong to the bachelor's degree program - again, a problem of separating the credential from what you have to do to get it.

If I'm way off base with any of this, let me know.

**Comment by siuc-nate** [comment]
Following our discussion today, we need to clarify the definition, and rename the property back to AudienceLevel.  We need to revisit Audience as well.  We need to finalize this property so that we can stabilize the definition of this property (we seem to keep going back and forth on whether this property defines who the credential is targeted towards vs what the credential is).

**Comment by stuartasutton** [comment]
:-) Yes, Audience Level.

**Comment by bobgsheets** [comment]
We also need to differentiate how it says something different than
credential requirement.

For example, some BA degrees say you need a HS diploma as a requirement for
pursuing my credential.  So, is the audience those with HS or is it saying
something more?   Some BSN programs require an ASN and not sure what they
would say about audience other than those with ASN.

I have tried to search websites of our pilot sites to get a sense of what
they are saying about audience that is different than requirements.

Need to other examples from our pilot sites where audience is saying more
than requirement

**Comment by jkitchensSIUC** [comment]
Other levels to include:
- Beginner/Novice (should this be just one of these?)
- Intermediate
- Advanced
- Expert

**Comment by stuartasutton** [comment]
Maybe it would help (maybe not) to look at the history of this vocabulary and property referencing it. In the beginning, the vocabulary was named AudienceLevel and it was the range of a property called typicalAudienceLevelType **on Credential**. Note that it had NOTHING to do with what is "required" or "recommended" etc. for the Credential. It was merely a way of saying quite directly and at the level of the Credential things like: 

>"The 'typical' audience (persons) for this credential are at the associate level (not a level attained, but **at that level**)". 

In other words, "This credential is intended for people just like me." Look at it's definition (back then and even now):

> "The typical level in an academic or training progression of the person seeking the credential." 

This vocabulary and its property are directly aligned with the Dublin Core [educationLevel](http://dublincore.org/documents/dcmi-terms/#terms-educationLevel) property with the definition of "A class of entity, defined in terms of progression through an educational or training context, for which the described resource is intended." Note that the Dublin Core property is a subproperty of dcterms:Audience defined as 'A class of entity for whom the resource is intended or useful." So, it's identifying a characteristic of the persons typically pursuing the credential. It's like: "Pursuit of this credential is intended for and useful to people in the 5th grade."  

I've not a clue what this has morphed into given changes that started on September 27th. Then (after internal discussions, I assume), the vocabulary was changed from AudienceLevel to EducationLevel, the number of concepts in the vocabulary reduced to the current level. Also, somewhere along the line, ConditionProfile was added as a domain triggering "requires", "recommends" etc. ...IMHO, way off the original intention.

**Comment by siuc-nate** [comment]
+1 to Stuart's comment

**Comment by siuc-nate** [comment]
Note: the classes and vocabulary spreadsheets are not in alignment on the name of this vocabulary:
https://docs.google.com/spreadsheets/d/1UINeEQbBvD1CZNYRjounCZE-xuvMyNDJZPrOGNcuFH4/edit#gid=0 has a URI of AudienceLevel and a Class of EducationLevel
https://docs.google.com/spreadsheets/d/1ir1wEF4R2wCG7UME--WJnlib6z1fLTdc5_icXbsAFz0/edit#gid=0 has a vocabulary for EducationLevel

**Comment by jkitchensSIUC** [comment]
On Nov 10, @siuc-nate @stuartasutton @bobgsheets and I reviewed this https://docs.google.com/document/d/1hRUMQ7kvdSDDO8A4dTWig5Yo7fpFFbX0zPmvfRl1OgQ/edit?usp=sharing 

he vocabulary was deemed sufficient only for cost and condition profiles.  It is likely not complete and may be extended later. However, two changes are needed as shown below. 

1. Update definition - The types of audiences for which the resource being described is applicable or available.

2. Update comment - If the resource is applicable or available for any type of audience, do not select anything.

Close this issue after making these updates.

**Comment by stuartasutton** [comment]
That's an error tat has not been corrected. When the AudienceLevel stuff was changed to EducationLevel, all of the necessary changes were not complete. They are now.

**Comment by jkitchensSIUC** [comment]
The Audience Level vocabulary documentation is here https://docs.google.com/document/d/1P-3EOR0U-pCuM4qqYsMwOEcfNRHxjHuNKcYHwv6E6SQ/edit?usp=sharing

Originally, we used Education Level.  This will need to be changed to Audience Level.  The vocabularies are being finalized based on partner input via a survey.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate Bob Sheets reviewed and included his changes to ctdlAudienceLevel.  He removed Expert Level (we need to be sure all references with the updated pending tables do NOT include Expert Level) and changed comments for the beginner, intermediate and advanced levels.  He is good with these changes now.  Please do a final review and these need to be changed in the Pending Viewer and added to the list to include with the scheduled February Release History.  Use this Google doc to see the table entries and notes below them https://docs.google.com/document/d/1P-3EOR0U-pCuM4qqYsMwOEcfNRHxjHuNKcYHwv6E6SQ/edit?usp=sharing

This is already included with ConditionProfile also need to add to Credential, LearningOpportunityProfile, and AssessmentProfile Classes.

Audience Level
Beginner Level
Intermediate Level
Advanced Level
Secondary Level
Post-Secondary Level 
   Associate's Degree Level
   Bachelor’s Degree Level
   Master’s Degree Level
   Doctoral Degree Level

The tables included with the aforementioned Google Doc include all updates.

**Comment by siuc-nate** [comment]
I have added the concepts:
- Beginner Level
- Intermediate Level
- Advanced Level
- Secondary Level
- Post-Secondary Level
- Associate's Degree Level
- Bachelor’s Degree Level
- Master’s Degree Level
- Doctoral Degree Level

I have removed the (old/existing) concepts:
- Associate
- Bachelor
- Doctoral
- Master
- SecondarySchoolOrEquivalent

Note: The document above includes references to postsecondary but does not define such a term. I have constructed it as follows (also, it is referenced varyingly as "Postsecondary", "PostSecondary", "Post-Secondary", etc. - which one is correct?):
URI: audLevel:PostSecondaryLevel
Label: Postsecondary Level
Definition: The resource is intended for postsecondary level individuals.

Note 2: The usage note and comment on Audience Level seem unnecessary and not in line with our other usage notes on other concept schemes (see my comments in the google doc itself). I think we should remove the comment and change the usage note to something along the lines of "Best practice is to use terms from the CTDL Audience Level vocabulary"

**Comment by stuartasutton** [comment]
For preLabel, I'd use "Post-Secondary Level" but for the URI "PostSecondaryLevel".

Agree on usage note.

**Comment by siuc-nate** [comment]
I have made these updates in pending CTDL:

Update audLevel:PostSecondaryLevel
Change Label from "Postsecondary Level" to "Post-Secondary Level"
Change Definition from "The resource is intended for postsecondary level individuals" to "The resource is intended for post-secondary level individuals"

Update ceterms:audienceLevelType
Change Usage Note from "Best practice for developing credential descriptions for the Credential Engine Registry is to use the CTDL AudienceLevel vocabulary." to "Best practice is to use terms from the CTDL Audience Level vocabulary."
