### ISSUE TITLE
Add ctdl:url to AssessmentProfile, LearningOpportunityProfile, and Organization

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#110]
I'm surprised these aren't already present.

Person might also need a URL.

**Comment by stuartasutton** [comment]
Bear in mind that when you add a ctdl:url (schema:url) to the profiles, you are saying that the profiles have a url and not that the thing they profile has a url.

**Comment by siuc-nate** [comment]
Per our conversation yesterday, I am reasonably sure that is what we want - it will enable referencing one profile from 1-n other profiles within the registry.  I'm open to responses/feedback on this though.

**Comment by stuartasutton** [comment]
In am RDF context, the URI is an inherent part of the resource. There is no need for a property to hold it. For example, here's a declaration in rdf/XML of the opening line of an AssessmentProfile with URI (i.e., not blank node):

\<ctdl:AssessmentProfile rdf:about="http://CredentialEngine.org/resource/64632f71c">

There is no property that "contains" the URI of this instance. Needing a property to express it is an artifact of an information model that has no built in notion of naming things with URI.

Even the JSON-LD doesn't need it. While probabaly not the best JSON, here the snipper opening a description of this same resource:

    "@id": "http://CredentialEngine.org/resource/64632f71c",
    "@type": "ctdl:AssessmentProfile",  

Why would we then need to include a property to tell us what @id already has?

**Comment by stuartasutton** [comment]
The use schema.org/url is to be able to markup the URL of a thing when it appears on a webpage...not because it is fundamental to the RDF that underlies schema.org

**Comment by siuc-nate** [comment]
It makes me wonder if we should instead be using @id for credential instead of url as well, then - and, do we need some kind of "targetUrl" property on each major object to point to the actual instances of credential/assessment/learning opportunity/organization?

**Comment by siuc-nate** [comment]
Thinking about it a bit more, I guess you could make the argument that "url" might be multivalue and/or might change over the life of the entity, whereas @id should be permanent (if I'm understanding correctly)?

Just a thought.

**Comment by stuartasutton** [comment]
As the URI naming an entity (@id) is conceptually permanent. ctdl:url/schema:url has no such notion attached.

**Comment by stuartasutton** [comment]
Nate (and @jkitchensSIUC ), we need to table this conversation about adding URI properties to more entities in the model until we can have a synchronous conversation and I can illustrate. That means we can't do it until I return from Europe. This is ***massively critical***, Nate, that you get the reason in terms of RDF (and how I think that plays out in JSON-LD). 

When we speak of instances of entities (all of them) in the CTDL model, they are all named (identified) either by URI or node ID for Bnodes. In neither case is there a need for a **property** like ctdl:url whose range is that URI...absolutely no need. That's true of JSON-LD as well where the value of @ID names (identifies) a resource not some property. 

The reason you see schema.org/url is so you can markup the URL in sentences like: "Fly-by-Night Credentials can be found at http://FlyByNight.com."  Notice that the range of schema.org/url is schema.org/URL which is TEXT. It's not a resource (thing); it is just a text string that begins with "http://....".  Good for displaying a URL to humans but useless as the URI/IRI naming/identifying a resource in RDF.

**Comment by stuartasutton** [comment]
@siuc-nate, @jkitchensSIUC, & @science, I know I asked to table this discussion until I got back from Europe and I have the time to demonstrate why I think adding cdtl:url/schema:url to all these entities is a BAD idea. I've had second thoughts about not trying to get my objection out on the table before I left for Europe (although its unlikely that I'll be able to follow a long thread of responses until I get back).

On our very fruitful call last Tuesday we talked about the addition of either entity URIs or bNodes  IDs ***to all entity descriptions*** in a description set (record). Because my concern was with identification of entities for data set loose in the wild as RDF/Linked Data, I said that I didn't care where/when those URIs or bnode IDs were added ***so long as they were present on export of the RDF record***. 

***I now have to go back on that*** and say that as a result of subsequent requests to pepper all these entities with ctdl:url properties, I have to care about the point in the lifecycle where these URIs/bnode IDs are added. If they are not coined and added at the point of record creation or ingest into the CER, then the lack of the "@id" in the JSON-LD apparently results in a lack that's driving the request to add a property like ctdl:url to convey the ID data we've said we weren't going to add at the point of ingest. That is the case because the URI range for such a property is exactly what the value would be of an "@id" (unless I am terribly off in terms of JSON encoding...always a possibility).  So, it you are going to add this ID data to such a property, why not just generate your "@id"s instead and be done.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate putting this on the agenda for tomorrow.

**Comment by jkitchensSIUC** [comment]
@siuc-nate add this to the URL wrap up documentation if it's still an issue https://docs.google.com/document/d/1H_M8WhPisqEab5MUEmz24wU4a76STn07NuSwXYywY8w/edit?usp=sharing 

If this is not an issue, include a closing comment and close.

**Comment by siuc-nate** [comment]
It's related in the sense that it's about URLs and thus I've included them in the URL spreadsheet - however, these URLs are special since they are the identifiers for the objects themselves. As it is currently, properties like "organization URL", "assessment URL", and "learning opportunity URL" are not a part of the schema, for the reasons Stuart outlines above. So the issue here is that we need to determine how to handle this information.

**Comment by siuc-nate** [comment]
Per our 11/14/2016 call, Stuart also wants ctdl:url added to ConditionProfile

@stuartasutton I do not understand the usage of this property - when or where would a ConditionProfile be referenced from some external entity (e.g. some Credential pointing to another Credential's conditions)?

**Comment by siuc-nate** [comment]
Refer to Issue #192

**Comment by siuc-nate** [comment]
This is still something we need to address

**Comment by stuartasutton** [comment]
This should be marked for the 2017-01-31 release. It needs subsequent discussion as to what ctdl:url (from schema.org/url) actually means in **our context**. 

 1. Is it some webpage for the thing (that's how the single example in schema.org is used)? If so, where exactly is the **webpage** for an AssessmentProfile (not the Assessment, the Profile)? Same with with LearningOpportunityProfile--where is the **webpage** of the Profile (not the LearningOpportunity)? Orgaization would likely have one, but not AssessmentProfile or LearningOpportunity ***if defined as a URL resolving to a webpage***. 

 1. Is it a URI of the thing being described. 

Until we have a settled definition that clears up potential uncertainty around meaning so it can be consistently used, I stand by my assertion that it is a BAD idea.

**Comment by siuc-nate** [comment]
Does it solve the problem to create purpose-specific URLs for the relevant profiles (e.g., "assessmentDescribed", "learningOpportunityDescribed") that point to the webpages for those entities?  Ultimately we need to be able to link a person using our system to the webpage for the resource.

**Comment by jkitchensSIUC** [comment]
Proposal:

- Keep ceterms:url with credential and all credential subclasses, and ceterms:GeoCoordinates?
- With all other profiles that have a web page specific to that resource being described, use the following property:

Term: resource
Label: URL 
Comment:
Definition: The web page where the substance of the resource being described is located.
Type of Term: rdfs:Property 
Range Includes: xsd:anyURI 
Equivalent Properties: 

This needs to be applied now to:
CredentialOrganization
QAcredentialOrganization
AssessmentProfile
LearningOpportunityProfile
CostManifest
ConditionProfile
RevocationProfile - note this profile already already has a URL ceterms:revocationCriteria
VerificationServiceProfile - note this profile already has a URL ceterms:verificationService

**Comment by siuc-nate** [comment]
We had also considered property names like "resourceDetails" or "resourceWebpage" to make it more specific.

We need to consider whether or not such a property would also be a part of Credential.

We would also need to make sure the documentation reflects the distinction between such a property and the CTID-based identifier we would want people to use to reference the profile from another profile (such as within/via the registry).

**Comment by stuartasutton** [comment]
I'd like to suggest the following modification:

>**Term:** subjectWebpage
**Label:** Subject Webpage
**Definition:** The web page where the subject of the resource being described is located.
**Comment:** The web page being referenced is the subject of the resource being described such as a learning opportunity being identified in a profile of that opportunity. The value of subjectWebpage is an authoritative location for information about the subject and should not assumed to be a persistent identifier of the subject.
**Subproperty Of:** schema:URL
**Type of Term:** rdfs:Property
**Range Includes:** xsd:anyURI
**Equivalent Properties:** [none]

I see no reason that ceterms:Credential should not also have this property.

@siuc-nate, I think the 'comment' handles your concern regarding the 'ctid'; however, it does not mention 'ctid' but is couched instead in terms of 'persistent identifier'. We need to do it this way since the the ctid is not universally required by the description language.

**Comment by stuartasutton** [comment]
...although ceterms:mainEntity (schema:mainEntity) would be just as valid (definition & comment the same):

>**Term:** mainEntity
**Label:** Main Entity
**Definition:** The web page where the subject of the resource being described is located.
**Comment:** The web page being referenced is the subject of the resource being described such as a learning opportunity being identified in a profile of that opportunity. The value of mainEntity is an authoritative location for information about the subject and should not assumed to be a persistent identifier of the subject.
Type of Term: rdfs:Property
**Range Includes:** xsd:anyURI
**Equivalent Property:** schema:mainEntity

**Comment by stuartasutton** [comment]
I lean toward ceterms:mainEntity...

**Comment by siuc-nate** [comment]
We reviewed the definition, usage, and examples of schema.org/mainEntity and its inverse, schema.org/mainEntityOfPage, and it seems that what we would want to use is the latter.  mainEntityOfPage is a property that points to a webpage for the "thing" being described - the example also matches what we would want to use and publish, as it is an object that indicates a type of "WebPage" and a URL to that page:

http://schema.org/mainEntityOfPage
{
    "context": "http://schema.org",
      "type": "Restaurant",
      "mainEntityOfPage": {
         "type": "WebPage",
         "id": "http://cathscafe.example.com/",
      },
      "name": "Cath's Cafe",
      "openingHours": "Mo,Tu,We,Th,Fr,Sa,Su 11:00-20:00",
      "telephone": "+155501003344",
      "menu": "/menu"
}

what are your thoughts?

**Comment by stuartasutton** [comment]
@siuc-nate OK...naming feels odd. 

Also, including the inverse would be problematic because of the load of entering both sets of data. In RDF and a triplestore, you **never** enter the data on both ends...only one. For example, let's assume that mainEntityOf and mainEntity ares declared as below. But, the person creating the data **only supplies** data for the statement noted as "explicit". An RDF reasoner on a triplestore would automatically infer and supply the triple for the inferred inverse statement.  That's the entailment of declaring things to be inverse. So in RDF-land, there are both **explicit triples** and **inferred triples**. Data entry provides the explicit and the reasoner provides the inferred triple. Because teh CER is not an RDF solution stack, this places the burden on the human entering data to add it to both ends. Maybe you can automate the behav

> Profile==mainEntityOfPage==>Credential **(explicit)**
Credential==mainEntity==>Profile **(inferred)**

...or the reverse

> Profile==mainEntityOfPage==>Credential **(implied)**
Credential==mainEntity==>Profile **(explicit)**

An RDF reasoner on a triplestore would automatically infer and supply the triple for the inferred inverse statement.  That's the entailment of declaring things to be inverse. So in RDF-land, there are both **explicit triples** and **inferred triples**. Data entry provides the explicit and the reasoner provides the inferred triple. Because the CER is not an RDF solution stack, this places the burden on the human entering data to add it to both ends. Different RDF stores handle this in different ways. Some stores create the inferred triple on creation or ingest and store it in the datastore while other stores may do the inferencing on the fly. But the result is that only half the data is supplied.

We also need to be careful with inverse declarations because there will be times when one thing (e.g., and Organization) and some other thing (by someone else) might be such that one side doesn't agree or care to have such an inference drawn. That was raise by Robby Robson in the one of the early TAC sessions.

Anyway, back to ceterms:mainEntityOfPage, go with it. BUT, I'd keep my revised definition and comment.

**Comment by siuc-nate** [comment]
Sorry, I didn't mean to imply that we would have both properties or that we would indicate our use of "mainEntityOfPage" was intended to be an "inverse" property - just that we reviewed schema.org/mainEntity and schema.org/mainEntityOfPage and that "mainEntityOfPage" happened to be the inverse of "mainEntity".

The main point was that the way schema.org defines and provides examples seems to indicate that "mainEntityOfPage" matches our purpose - some property to indicate the URL of a webpage about a resource being described in a given profile.  The way it defines and provides examples of "mainEntity" would imply that the publisher needs to embed the profile within itself.  I guess what we're really trying to say is closer to "main**PageFor**Entity"  To that end, how about something like this:

Term: **subjectWebpage** (to avoid potential "mainEntity" confusion)
Label: Subject Webpage
Definition: The web page where the subject of the resource being described is located.
Comment: The web page being referenced is the subject of the resource being described such as a learning opportunity being identified in a profile of that opportunity. The value of subjectWebpage is an authoritative location for information about the subject and should not assumed to be a persistent identifier of the subject.
Subproperty Of: schema:URL
Type of Term: rdfs:Property
Range Includes: xsd:anyURI
Equivalent Properties: **schema:mainEntityOfPage** (per the above comments)

**Comment by stuartasutton** [comment]
Looks good to me!

**Comment by siuc-nate** [comment]
I have added the property:
http://credreg.net/ctdl/terms/subjectWebpage

**Comment by stuartasutton** [comment]
I notice that `subjectWebpage` has no domain identified.

**Comment by stuartasutton** [comment]
A correction to `subjectWebpage` -- remove the subproperty `schema:url` since we declare the property equivalency to `schema:mainEntityOfPage` and it declares no such relationship. 

(Note: While we need to remove `schema:URI`, I'd not that we ned to be careful. We "URL" in all caps denoting the `schema:URL` class as opposed to the `schema:url` property)

**Comment by siuc-nate** [comment]
Whoops, I was following the post so closely, I didn't notice there was no domain included.  My mistake.

The domain should be:
- ctdl:Credential (and its subclasses)
- ctdl:CredentialOrganization
- ctdl:QACredentialOrganization
- ctdl:AssessmentProfile
- ctdl:LearningOpportunityProfile

Correct?

**Comment by siuc-nate** [comment]
I have made the above corrections.
