### ISSUE TITLE
Add "copyrightHolder" properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#115]
Currently only credential has a "copyrightHolder" property.  This should be added to other profiles where it may apply, and a reverse property (perhaps "copyrightHolderFor"? I have no strong feelings about the name) should be added to Organization.

**Comment by stuartasutton** [comment]
The only two where it makes sense would be AssessmentProfile where it is applicable to the Assessment being profiled and the LearningOpportunityProfile where it applies to the LearningOpportunity being profiled.

**Comment by stuartasutton** [comment]
And, I'd use "copyrightHolderOf"--"of", not "for"

**Comment by siuc-nate** [comment]
Do you intend to add this or would you like us to do it?

**Comment by stuartasutton** [comment]
Given a bit more thought, would copyright information for a LearningOpportunity or an Assessment be best left to descriptions of those entities and not their profiles here in a Credential record? I ask because any changes to those legal interests would need to reverberate upstream from those description of the actual Assessment or LearningOpportunity (e.g., a course description) to their profiles. Seems like a lot of maintenance when the copyright on those entities could be derived by simply following the links from their profiles to the the entity description. To repeat the data is not very RDF/linked data-like.

**Comment by siuc-nate** [comment]
In that case, should copyrightHolder be removed from the Credential class?

**Comment by stuartasutton** [comment]
No. Credential should be left alone. A credential has a copyright holder as do actual assessments and actual learning opportunities have them. While a learning opportunity profile has them in theory, a copyright holder statement could mean rights in the profile OR rights in the thing profiled (which could.be a different holder).

**Comment by siuc-nate** [comment]
So there is to be no action taken then, correct?
