### ISSUE TITLE
Property(ies?) to express equivalence or similarity

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#128]
We had previously discussed needing to add properties to allow expressing that one credential was roughly equivalent to another credential; however, I do not see such properties anywhere in our properties spreadsheet.  Were these ever added?

**Comment by stuartasutton** [comment]
I do not recall the conversation beyond the infamous sameAs (which we do not want to do). But, that said, it is not hard. Take a look at issue #134 since I mentioned the ASN "strength of fit" properties with Bob. It would mean defining an equivalent property relationship with ASN and define it as credential-to-credential matching.

**Comment by stuartasutton** [comment]
Also, I'll have to do a bit of digging, but we actually developed a decision-tree for picking the right match for a particular circumstance.

**Comment by siuc-nate** [comment]
This would effectively be the equivalent of https://schema.org/isSimilarTo but with the potential for putting a condition profile in the middle in order to allow expressing weight - see my comment on #134 for more thoughts on this.

**Comment by stuartasutton** [comment]
See second 1/2 of issue #128; those properties have been included (on Credential alone at this point).

**Comment by siuc-nate** [comment]
This is resolved by the addition of the isSimilarTo property and its refinements as discussed in #134
