### ISSUE TITLE
Can `ctid`'s be used without registering them with CER?

### ISSUE THREAD

**Issue by science** [CredentialTransparencyInitiative/vocabularies#163]
I can't remember the final decision on the use of ctid's "in the wild" that are not registered with CER. Is this permissible? I'm writing up our URN application and this is relevant information.

Specifically, I can imagine a credential publisher who wishes to publish metadata about a credential on their website using CTDL. But they don't (for whatever reason) want to publish it to CER. Can they (according to our spec for the ctid's) create a `ctid` and put that on their website along with the rest of their metadata?

My thinking is that they *cannot* do this b/c there's not way to resolve that `ctid` to anywhere if it is found elsewhere in the wild? The only way to resolve a ctid is to register it with CER.

Am I right on this point?

cc @stuartasutton @mparsons1953 @jkitchensSIUC

**Comment by stuartasutton** [comment]
@science, the difficulty with the question is that there is no way in the wild to stop someone from creating a CTID since anyone that can generate a UUID can generate a "technically" legitimate CTID. So, in the wild, they can and they will do so. The only thing that makes that difficult for such people ***in the short term*** is that our only public documentation at the moment doesn't describe the structure of a CTID (http://www.credreg.net/page/propertiesviewer#ctid). Long-term, that would change as people see instances of CTID and understand their structure.

I recall from our discussions that what CER does in terms of an non-registered CTID received in data is obviously not resolve it and send some kind of error message. But I don't really remember any determination of exactly what to do.

**Comment by jkitchensSIUC** [comment]
@science @stuartasutton @mparsons1953 @CTITechPlanning @siuc-nate we have the following documentation

- TAC presentation on July 22, 2016 - https://docs.google.com/presentation/d/15_odCx6kjhfyJcG0CTd-wA-EtZDY5OIF9_RuB6Fk1Kc/edit?usp=sharing

- TAC document on July 22, 2016 https://docs.google.com/document/d/1sEKgTNT5aIEOhoL2KkRDw4zuQ5FMewSkMNW4DUoWN1M/edit?usp=sharing

- Related July 22nd Folder with scribing notes https://docs.google.com/document/d/1sEKgTNT5aIEOhoL2KkRDw4zuQ5FMewSkMNW4DUoWN1M/edit?usp=sharing

- CTID internal planning folder is here https://drive.google.com/drive/folders/0B1uSTaYpjhXJdjM1V21odGZWVUE?usp=sharing

I'm putting this on the agenda for this week.

**Comment by jkitchensSIUC** [comment]
@mparsons1953 the documentation needs to state the CER resolves CTIDs generated by the registry not those in the wild. However, there's nothing to prevent them from being generated in the wild.
