### ISSUE TITLE
Non-vocabulary terms and PURLS

### ISSUE THREAD

**Issue by mparsons1953** [CredentialTransparencyInitiative/vocabularies#173]
@stuartasutton 
There is a 'non-vocabulary' tab on the  Vocabulary spreadsheet. For example:
![image](https://cloud.githubusercontent.com/assets/16601156/20110490/28c2300c-a5aa-11e6-8a7a-0be696b1d703.png)

Are there PURL implications for these? The syntax looks like the vocabulary format, but I understand that they are different. Or would we just need to ensure that from the 'terms' page for CredentialType (for example), that we show all these terms?

**Comment by stuartasutton** [comment]
Mike, please use *only* the Vocabulary Terms tab from the Vocabulary
Inventory V2 spreadsheet (
https://docs.google.com/spreadsheets/d/1ir1wEF4R2wCG7UME--WJnlib6z1fLTdc5_icXbsAFz0/edit#gid=0
).

Nate can fill you in on what the other tabs to the spreadsheet are for.
However, the Vocabulary Terms tab is the only one I monitor, update etc. I
think some of those tabs are just for archiving...but Nate created them.

**Comment by siuc-nate** [comment]
A long time ago, in the middle of one of our meetings, we decided to remove the credential type vocabulary (and a few other things) from the vocabulary spreadsheet since they were not _true_ vocabularies (at that time).  I did not want to lose the data, however, so I created the "non-vocabulary items" sheet and cut/pasted the relevant rows to that so they would not be lost.

Since then, I am not sure what the status of the credential type vocabulary is.
