### ISSUE TITLE
Proposal to add ctdl:conditionItem Property to ctdl:ConditionProfile

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#187]
ctdl:ConditionProfile
http://credreg.net/page/domainsviewer#ConditionProfile  

Issue: This profile has a top-level "Description" used across profiles. The same "Description" is used to create multiple condition profiles causing the description to lose context. The examples below illustrate the issue.  

Proposed Solution: add a property to Condition Profile:
ctdl:conditionItem
Label: Condition Item
Definition: An individual condition.
Comment:
Type of Term: rdf: Property
Range: Literal
Domain: ctdl:ConditionProfile

Examples are illustrated with a Google Doc https://docs.google.com/document/d/1d85Y1mUhISFxv4rWvuojIJtMFxH_DfmWrBZVLTv0rh0/edit?usp=sharing

**Comment by stuartasutton** [comment]
Seems reasonable; although not enamored with tacking "item" onto a ctdl:condition property. I think adding the subcondition option would be good with an additionalCondition property declared as subproperty of hasPart with range of ConditionProfile. I changed that from subConditions because it is unclear from the example how the additions are sub(ordinate) as opposed to additional. Also, I assume that all three additional ConditionProfiles are cumulative (i.e., "in addition to" the conditions of the parent ConditionProfile):

(1) Take assessment, Submit Transcripts, Masters Degree
(2) Take assessment, Submit Transcripts, 2 Years in Relevant Field, Bachelor's Degree
(3) Take assessment, Submit Transcripts, 7 Years Work Experience, Take LearningOpportunity.

**Comment by jkitchensSIUC** [comment]
Based on the CTDL review on Nov 14, 2016 determined the following changes need to be made to Condition Profile as follows:

ctdl:condition
Label: Condition
Type of term: rdf:Property
Subproperty Of: ctdl:Description
Range: Literal
Domain: ctdl:ConditionProfile
Definition: A list of individual conditions or aspects of experience.
Usage Note:

ctdl:additionalCondition
Label: Additional Condition
Type of term: rdf:Property
Range: ctdl:ConditionProfile
Domain: ctdl:ConditionProfile
Definition: An additional set of conditions.
Usage Note: In the context of requirements, select at least one of the conditions listed here to fulfill the parent conditions.

**Comment by stuartasutton** [comment]
**ACTIONS TAKEN**

The following have been added:

> http://www.credreg.net/page/propertiesviewer#condition
http://www.credreg.net/page/propertiesviewer#additionalCondition
