### ISSUE TITLE
Consider adding CredentialAlignmentObject to range of requires & recommends

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#188]
Looking to a "thin" version of the CTDL, we need to be able to say **directly** that an instance of Cedential requires or recommends a Competency (or set of competencies) without having to go through the complexity of a ConditionProfile instance. That means being able to say either/or/both the following:

```
Credential==requires==>AlignmentObject (type Competency)
```
**or**
```
Credential==requires==>Competency (for direct RDF linking)
```

At a minimum, that means adding CredentialAlignmentObject as range to the [requires](http://www.credreg.net/page/propertiesviewer#requires) and [recommends](http://www.credreg.net/page/propertiesviewer#recommends) properties.

**NOTE:** This is not a 2016-11-17 issue and has been milestoned with "Release -Subsequent".

**Comment by jkitchensSIUC** [comment]
@stuartasutton +1.  @siuc-nate provide input.

**Comment by siuc-nate** [comment]
The intended usage of the "requires" field is to, via ConditionProfile, indicate "a complete set of requirements". If this field points to a competency, it would be saying that "all you have to do is have this competency to earn this credential." How would someone go about "proving" that they have that competency? There is no facility to link to an assessment or any other action in this case.

Furthermore, I assume most credentials would have more than one required competency; if each competency is interpreted as a "complete" set of requirements (because each competency's alignment object is attached to "requires") then that would be very problematic.

Ultimately I would prefer having separate properties along the lines of "requiredCompetency" and "recommendedCompetency", and documenting that these are **not** indicative of the sum total of things someone must do to earn a credential. 

However, if the above problems can be **sufficiently** handled via documentation (e.g., "this only defines a complete set of requirements if it points to a ConditionProfile") _and_ there is no risk of trouble if and when a Credential has _both_ one or more ConditionProfiles _and_ one or more CredentialAlignmentObjects underneath the roof of "requires", then perhaps we could extend the range.  But I am very hesitant to go along with that.

**Comment by siuc-nate** [comment]
Per our discussion on 11/28/2016, I will create some diagrams of potential scenarios so we can discuss how the documentation should describe how those scenarios should be interpreted and handled by users of CTDL.

**Comment by siuc-nate** [comment]
I think we should move this to a different release.

**Comment by stuartasutton** [comment]
The 2170131 release you be fine

**Comment by siuc-nate** [comment]
I have created a few diagrams to display the points I was attempting to make in that call and explain why I think we should not add CredentialAlignmentObject to the range of requires, recommends, etc.  Namely:
- Consistent use of ConditionProfile preserves the ability to create multiple routes to attain a credential
- ConditionProfile is necessary in order to relate sets of requirements together, particularly (but not exclusively) as they relate to multiple routes
- Attempting to use both ConditionProfile and CredentialAlignmentObject creates confusion as to what the actual requirements (or recommendations, etc.) are.
- Use of multiple CredentialAlignmentObjects muddies the meaning and usage of the "requires" property: One complete "requires" property = 1 successfully attained credential. This is not true if a credential requires 3 competencies and a Credential has 3 "requires" arrows connecting it to those competencies.
- ConditionProfile provides additional facilities (via its own properties) to describe other requirements in addition to competencies (e.g., description, condition(item), minimumAge, yearsOfExperience)
- There is an implication that there would need to be a connection type + condition property combination property, for every combination of connection and property, in order to avoid the ambiguity of "requires" pointing to "some object" that requires retrieval and inspection. For example:
   - requiresMinimumAge
   - recommendsYearsOfExperience
   - preparesForTargetAssessment
   - advancedStandingFromTargetLearningOpportunity
   - and so on - potentially **hundreds** of new properties.

Case 1: Simple competency requirement
In this case, it is simpler to do without the indirection of a ConditionProfile.  However, the issues below illustrate why I do not believe this is worthwhile.
![image](https://cloud.githubusercontent.com/assets/21346519/20903204/1957b6e4-bb00-11e6-864f-967b03d175c9.png)

Case 2: Simple multi-competency requirement
In this case, the meaning and usage of "requires" has been disrupted by using multiple "requires" to indicate a _single_ set of requirements:
![image](https://cloud.githubusercontent.com/assets/21346519/20903250/37ffb902-bb00-11e6-974d-45f1558adebd.png)

Case 3: Compound requirements
In this case, a ConditionProfile became necessary to convey additional information - but now it is not clear whether those conditions are part of a single route, or if they stand on their own, or to which (if any) of the competencies they relate:
![image](https://cloud.githubusercontent.com/assets/21346519/20903300/6d35837c-bb00-11e6-9ba0-90bf6249d5a7.png)

Case 4: Multi-pathway requirements
This is the primary reason ConditionProfile was originally invented. Without this mechanism, there is no way to group information together, meaning the consumer has no way to know which things they must complete or which cost(s) they must pay in order to attain the credential:
![image](https://cloud.githubusercontent.com/assets/21346519/20903654/c4e0df58-bb01-11e6-9e77-c32560cb58ee.png)
![image](https://cloud.githubusercontent.com/assets/21346519/20903667/d85b908c-bb01-11e6-8c2d-c1c405579073.png)

Case 5: Hybrid approach
Attempting to use both ConditionProfile and CredentialAlignmentObjects at the same time decontextualizes the information (see Case 4) and muddies the meaning of "requires" (see Case 3). It also creates confusion for information entry/markup - for example, should the AssessmentProfile in the second image below be placed as a "targetAssessment" of its ConditionProfile, or "bubbled up" and displayed as a (standalone?) requirement for the Credential? How would the documentation indicate which decision to make, and when, and why? How would the documentation instruct a consumer of this information to interpret it?:
![image](https://cloud.githubusercontent.com/assets/21346519/20903720/0e00d24c-bb02-11e6-8c4a-dddfbe79ff61.png)
![image](https://cloud.githubusercontent.com/assets/21346519/20904495/638a5a1e-bb05-11e6-86c7-32ae7318ca6f.png)

Case 6: Complex example
This example illustrates the use of the "additionalCondition" property. Without consistent use of "requires" and ConditionProfile, these sub-conditions cannot be clearly associated with the correct hierarchy of information. **Note:** This also illustrates why "bubbling up" information on the prototype app's detail page creates the potential for confusion and inaccuracy - the user has no context or grouping for information that is extracted and displayed outside of its ConditionProfile, because it all appears at the Credential "layer", thus making it appear that all requirements from all pathways must be met in order to attain the credential. This is especially impactful for costs, since we become unable to relate a cost to a specific resource or set of requirements:
![image](https://cloud.githubusercontent.com/assets/21346519/20903902/e0129482-bb02-11e6-8e36-6aedeae68649.png)
![image](https://cloud.githubusercontent.com/assets/21346519/20903921/ed9a3452-bb02-11e6-85dc-6162c4a439bd.png)

I would propose that, if we still want to directly relate a Credential to a competency, we do so with a new property (along the lines of "requiredCompetency") along with clear documentation that explains how it relates to the "requires" property (e.g., "Items listed as targets of requiredCompetency apply to **each set** of requirements listed as targets of the "requires" property of the resource being described").

**Comment by stuartasutton** [comment]
I suggest we hold these additions until we have a group convened to look at the CTDL "thin".

And, by the way, doing subpropertis on key properties is not a bad idea--e.g. requiredCompetency, requiredAssessment etc. in solid linked data, that is exactly what would happen. The result is more precise semantics...and, no, it would not have to be every property current pointing to ConditionProfile..

**Comment by siuc-nate** [comment]
Holding off until then makes sense.

Even if we had all of those properties, we would still be up against the problem of not being able to group the information together - that is the primary purpose of ConditionProfile.

**Comment by siuc-nate** [comment]
Per our call on 12-7-2016, some suggestions/ideas:
- Addition of a "requirementSet" property that exists to explicitly point to one or more complete sets of requirements (via ConditionProfile)
- Addition of a "recommendationSet" property that exists to explicitly point to one or more complete sets of recommendations (via ConditionProfile)
- Addition of various classes (AssessmentProfile, LearningOpportunityProfile, Credential, TaskProfile, etc.) to the range of requires and recommends
- Potentially changing "ConditionProfile" to "ConditionSetProfile"

**Comment by stuartasutton** [comment]
Just to add a few notes to Nate's summary of the discussion regarding adding `CredentialAlignmentObject` to the range of `requires` and `recommends` so we have as complete a record of the discussion as possible when this is picked up by the group looking at CTDL 'thin', both of us agree that the problem of whether these two properties should be able to point directly to `CredentialAlignmentObject` can be thought of in terms of the complexity (or lack thereof) of particular requirements or recommendations. Not all requirements or recommendations are complex, and yet, with one exception, we currently treat them all as complex (i.e., they have to trigger an instance of `ConditionProfile`). That one exception is that `requires`, `recommends' (as well as all the other `Credential` to `ConditionProfile` properties allow pointing directly to `Credential` in the following manner:

```
Credential==requires==>Credential
Credential==recommends==>Credential
```

**Comment by siuc-nate** [comment]
This change has been made and added to history tracking.

Note: our discussions of the actual usage of requires and the recent addition of ceterms:alternativeCondition covers the use case I outlined in the above posts.
