### ISSUE TITLE
Update domain and range of isSimilarTo to match its subproperties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#210]
Currently it has no domain and only has a range of xsd:anyURI

**Comment by stuartasutton** [comment]
YES. **And that is correct.** The property is used as the super-property for all of the identify mapping properties and has not been assigned a domain for use on its own because it is too broad to have much meaning. BUT, as a superclass, it provides downstream systems with the ability to dumb-down more refined properties that it does not understand to "isSimilarTo"; and (2) provides a broad umbrella class for tying together all things similar.

See:

> http://www.credreg.net/ctdl/terms#broadAlignment
http://www.credreg.net/ctdl/terms#narrowAlignment
http://www.credreg.net/ctdl/terms#exactAlignment
http://www.credreg.net/ctdl/terms#majorAlignment
http://www.credreg.net/ctdl/terms#minorAlignment

**Comment by stuartasutton** [comment]
NOTE: Edited my response above because it originally said "Yes", do it when it meant "no" don't do it!

**Comment by siuc-nate** [comment]
Just to clarify - in a system like our prototype, we would want to restrict people from selecting "isSimilarTo" as an option; we would instead want them to pick one of the subproperties, correct?

**Comment by stuartasutton** [comment]
YES!
