### ISSUE TITLE
Documenting ceterms:ConditionProfile

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#240]
I have started to document ceterms:ConditionProfile and have developed the following graphic of application of "requites". I want to run it past you for a reality check.

![2016-11-26-condition_illustration](https://cloud.githubusercontent.com/assets/2939046/20641792/84827d62-b3b4-11e6-9f70-188f304572dd.png)

**Comment by siuc-nate** [comment]
The diagram is technically correct (except that targetPathway points to a CareerPathway class rather than an AssessmentProfile), but it would probably be more effective to show how ConditionProfile is used to describe multiple sets of conditions (i.e., pathways to attain a credential) in addition to showing the types of entities that a ConditionProfile can point to.  It may also be a good idea to include showing a ConditionProfile that references subordinate ConditionProfiles via the additionalCondition property.

**Comment by siuc-nate** [comment]
Can this be closed?

**Comment by stuartasutton** [comment]
As long as it is without comment. It's going into the documentation as part of an "explanation".

**Comment by siuc-nate** [comment]
This will be fine.
