### ISSUE TITLE
Define Assessment, Learning Opportunity, and Learning Resource

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#250]
@stuartasutton This is not regarding AssessmentProfile or LearningOpportunityProfile; this is regarding Assessment, LearningOpportunity, and LearningResource.  These classes have no properties.  If they should have properties, we should define them; otherwise, we should drop them.

http://credreg.net/ctdl#Assessment
http://credreg.net/ctdl#LearningOpportunity
http://credreg.net/ctdl#LearningResource

**Comment by stuartasutton** [comment]
No, rational is off. They have no properties because we don't intend to describe them. But they are useful as classes to which resources described by other are members. We also have CredentialAssertion that has no properties  but it is useful to say we don't describe things of the CredentialAssertion class that has mysteriously gathered properties where it should not ... "expand"?

**Comment by jkitchensSIUC** [comment]
We discussed this on November 29, 2016 and clarified this.  No changes were needed/made.
