### ISSUE TITLE
Add Properties: Major, Minor and Concentration Only to Degrees

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#265]
Add Properties: Major, Minor and Concentration only to Degrees.   
Add to Pending schema. 
As background, this addition was brought forward by Eric Korb.  We need to follow up with him on this. 
Notify TAC of this as pending with Feb. release date.

**Comment by siuc-nate** [comment]
I assume these would all point to CredentialAlignmentObject?  Or would they be subproperties of subject, per one of Stuart's suggestions (and thus have a range of either Literal or CredentialAlignmentObject)?

**Comment by stuartasutton** [comment]
Once carefully defined (and they haven't been yet), the range should be CredentialAlignmentObject. There is no need for adding literal since literals for name targetNodeName (and targetNodeDescription) are already accommodated in CredentialAlignmentObject. Also, to better align with the National Student Clearinghouse DegreeVerify, the definition for all three should recommend use of CIP to identify all three "if possible" (or some other recognized framework defining majors, minors and concentrations for more international scoping).

No, I do not think these are subproperties of subject. They are entirely different beasts semantically and the feeling that they are "subjects" (i.e., denote "aboutness") is coincidental. It's one thing to say that something is about physics and another to say the concentration of a master of science degree is physics. People looking for resources dealing with a concentration in physics are not likely to be satisfied with a retrieval set filled with resources about physics.

**Comment by stuartasutton** [comment]
PROPOSED DEFINITIONS:

> **Major:** The primary field of study of a degree-seeking student.
**Concentration:** A structured plan of study within a degree major.
**Minor:** An optional, secondary field of study of a degree-seeking student.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate see this Google Doc.  It includes the proposed definitions in blank tables to fill in https://docs.google.com/document/d/1Rilo3NUahKCjWhHFQI8ZBoymmzOWUTKpcaTJZ-JPgnI/edit?usp=sharing

**Comment by jkitchensSIUC** [comment]
The following properties were added to Pending on 12/15/2016:

ceterms:degreeConcentration - http://credreg.net/ctdl/pending#degreeConcentration 
ceterms:degreeMajor - http://credreg.net/ctdl/pending#degreeMajor
ceterms:degreeMinor- http://credreg.net/ctdl/pending#degreeMinor

**Comment by siuc-nate** [comment]
Noted in history tracking.
