### ISSUE TITLE
Change ceterms:agent to ceterms:actingAgent

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#286]
In order to avoid confusion between ceterms:agent and ceterms:Agent (and be more consistent with the rest of our schema), this change should be made.

**Comment by stuartasutton** [comment]
I have no objections

**Comment by siuc-nate** [comment]
Would this be done by changing the existing term or adding ceterms:actingAgent and deprecating ceterms:agent?

**Comment by stuartasutton** [comment]
actingAgent would be OK...although I'm not massively concerned about the fact that the same lexical string is present in both class and property.

**Comment by siuc-nate** [comment]
It makes life easier in many ways to avoid the same string, I've found.  Anyway, should the history note reflect that "ceterms:agent" was dropped and "ceterms:actingAgent" was added, or should it reflect that "ceterms:agent" was changed to "ceterms:actingAgent"?

Or does it matter?

**Comment by stuartasutton** [comment]
Well. yes, it matters. We need to deprecate the current property URI and not just change it because people might have systems already using the old one. We should assign a status of `deprecated` which keeps the old one around and functioning. Then relate the deprecated property to the new one using the schema.org meta property [`supersededBy`](http://schema.org/supersededBy). Needs to be in release history so TAC can see and comment on the change before it happens.

If the deprecated property shows up in the TOC for properties, it really should show "deprecated". 

Actions to be taken:

1.  Add `ceterms:actingAgent` prpperty retaining the current description;
2. Add the following properties to current description of `ceterms:agent` 
* `schema:supersededBy ceterms:actingAgent`; 
* `vs:term_status "deprecated"@en-US`

So, the overhead on these kinds of actions is rather high, but unavoidable in terms of the integrity of language management. I think (but am not certain) that the schema.org notion of the ['attic'](http://attic.webschemas.org/StupidType) is somehow used to set aside deprecated stuff from regular view while keeping it available for legacy systems (haven't tested this notion).

**Comment by siuc-nate** [comment]
I have noted this in the history.

**Comment by siuc-nate** [comment]
Actions to be taken:

Create 
ceterms:actingAgent
Label: Acting Agent
Definition: The direct performer or driver of the action (animate or inanimate).
Usage Note: The organization or person performing the action.
Domain: ceterms:CredentialingAction
Range: ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:CredentialPerson
Equivalent To: schema:agent

Change
ceterms:agent
status: vs:deprecated
meta:supersededBy: ceterms:actingAgent

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
