### ISSUE TITLE
Refine handling of locations and contact information for organizations

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#307]
After meeting about this, we boiled several approaches down to a (relatively) simple proposal:
https://docs.google.com/drawings/d/1vowSx9aUspt3UT2kjnfk5q4JCkcu6nsQrPxrFKEQ3wI/edit

We would like to get input from @stuartasutton  before moving on, however. 

The problem we have is the need to associate contact information and address information while not merging those two profiles (as it is useful to be able to define them separately too).

**Comment by stuartasutton** [comment]
First, defining them separately is no problem since that's already the case--`ContactPoint` and `PostalAddress`. So solving the issue is just the adding and deleting of a few properties. As far as I can tell, the only new additions are: (1) `description` and `contactPoint` to `PostalAddress` and deletion of `email`, `faxNumber`, and `telephone`; (2) `contactOption` and `socialMedia` (new) to `ContactPoint`; and (3) `socialMedia` to `CredentialOrganization`. We should resist renaming `contactPoint`--our pattern mirrors schema.org and triggering a deprecation/supersededBy seems like a high price.

A new `socialMedia` property should likely follow the same approach as [Google's handling guidelines](https://developers.google.com/search/docs/data-types/social-profile-links#guidelines) for social media links in markup except we use the new property `socialMedia` as opposed to Google's use of `sameAs`.  Use of `sameAs` would work if the social media referenced was actually a surrogate for the organization, but not so much when it's something like the orgs' YouTube channel.  So, on `CredentialOrganization` that would look like the following in turtle and jsonld (also just substitute `ContactPoint` for `CredentialOrganization`--solution is the same) :

**Turtle**

```
@prefix ceterms: <http://purl.org/ctdl/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix res: <http://example.org/resources/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

res:61183b59-0669-457b-881a-a2b3bedcafdc a ceterms:CredentialOrganization ;
    ceterms:name "Santa Rosa Junior College"@en-US ;
    ceterms:socialMedia <https://www.facebook.com/santarosajc>, 
        <https://www.linkedin.com/company/santa-rosa-junior-college>,
        <https://plus.google.com/116220287386002204912>, 
        <https://www.youtube.com/user/srjcmediaservices> .
```
**JSONLD**
```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "res": "http://example.org/resources/",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@id": "res:61183b59-0669-457b-881a-a2b3bedcafdc",
  "@type": "ceterms:CredentialOrganization",
  "ceterms:name": {
    "@language": "en-US",
    "@value": "Santa Rosa Junior College"
  },
  "ceterms:socialMedia": [
    {
      "@id": "https://www.linkedin.com/company/santa-rosa-junior-college"
    },
    {
      "@id": "https://www.youtube.com/user/srjcmediaservices"
    },
    {
      "@id": "https://plus.google.com/116220287386002204912"
    },
    {
      "@id": "https://www.facebook.com/santarosajc"
    }
  ]
}
```

**Comment by siuc-nate** [comment]
That sounds good to me, Stuart.  So, to formalize the list of actions for the February release (@stuartasutton can you verify that these are correct?):

Deprecate ceterms:contactPoint

Create ceterms:targetContactPoint
Label: Target Contact Point
Definition: Options for contacting the resource being described.
Domain: ceterms:CredentialOrganization, ceterms:QACredentialOrganization. ceterms:PostalAddress
Range: ceterms:ContactPoint

Update ceterms:ContactPoint
Definition: A means of contacting an organization or its representatives.
Comment: For example, a public relations email address or phone number.

Create ceterms:contactOption
Label: Contact Option
Definition: An option available on this contact point.
Comment: For example, a toll-free number or support for hearing-impaired callers.
Domain: ceterms:ContactPoint
Range: rdfs:Literal

Create ceterms:socialMedia
Label: Social Media
Definition: A social media resource for the resource being described.
Domain: ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:ContactPoint
Range: xsd:anyURI

Update ceterms:email
Remove Domain: cetermsPostalAddress

Update ceterms:faxNumber
Remove Domain: ceterms:PostalAddress

Update ceterms:telephone
Remove Domain: ceterms:PostalAddress

**Comment by siuc-nate** [comment]
I have made these changes in pending CTDL and noted them in the history tracking.
