### ISSUE TITLE
Need to add QA usage indication to Organization (or to Credential?)

### ISSUE THREAD

**Issue by CTITechPlanning** [CredentialTransparencyInitiative/vocabularies#4]
From https://docs.google.com/document/d/13NxPR4l4iAuZ5IseRtSzfh61Jj3F6q15NMP2ToYjDhM/edit

Example data:
How the quality assurance (accreditation, endorsement, approval, licensure, recognition) is used:
- Federal, state, or local requirements
- Assists employers seeking competent practitioners
- Promotes professional advancement and career mobility of program graduates

**Comment by stuartasutton** [comment]
This seems clearly to be an attribute of Credential and not Organization since this "use" is of a particular Credential and a single Organization might easily have various Credentials where the use(s) might well be different.

**Comment by stuartasutton** [comment]
The more I look at this, the less convinced I am it can be used in a way that is useful to end users. It would be, at best, an ***intended*** use of the creator since users might use it for any or all of the three usage contexts identified in the bulleted list. So would a property on Credential be [[useContext]], or [[intendedUseContext]]. 

And that still does not solve the utility problem for me since the Credential creator might have an intended purpose to "Assist employers..." and the end use might see it's use through his or her lens as "Fed, state requirement".

**Comment by stuartasutton** [comment]
Resolved by defining { ctdl:purposeType } (subproperty of schema:purpose) with a range of the CTI vocabulary { ctdl:IntendedPurpose }.
