### ISSUE TITLE
Credential Connections Properties for Advanced Standing

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#42]
Define advanced standing as a credential to credential relationship.  This is to handle advanced standing for another credential.  The credential provides advanced standing in the pursuit of another credential that reduces the time and cost for attaining that credential (e.g., credit transfer).  Use case #28 http://www.credreg.net/page/usecasesviewer

**Comment by siuc-nate** [comment]
Is this ultimately just a CTID/URL that points to another credential? e.g.:

`{
"@type": "ctdl:Credential",
"providesAdvancedStandingFor": [
"http://credentialurl.com/1234"
]
}`

Or is this data to be more complex?

**Comment by siuc-nate** [comment]
Nevermind, discussed it with Stuart - it points to a condition profile.

**Comment by stuartasutton** [comment]
Nate, your take here is not necessarily wrong.  My suggestion is that the range be *both* ConditionProfile or Credential. Here is an image from my 2016-07-22 presentation that shows a full array at te CTDL level of Credential-to-Credential properties with domains of **both** Credential **and** ConditionProfile. 

![2016-07-22-tac-credential-to-credential](https://cloud.githubusercontent.com/assets/2939046/18207709/1ef6ea3e-70e1-11e6-9bbd-b35df1e8c6b9.png)

I'd like to see the advanced standing property have these dual ranges.

**Comment by stuartasutton** [comment]
From discussion yesterday (and the agenda notes), I have added the following two properties:

1. **ctdl: advancedStandingFor** (Credential 'A' says it provides advanced standing for Credential 'B)': domain=Credential; range=ConditionProfile and Credential (see: http://www.credreg.net/page/propertiesviewer#advancedStandingFor);
2. **ctdl:providesAdvancedStanding** (Credential 'B' says Credential 'A' provides advanced standing for it (Credential 'B')): domain=Credential; range=ConditionProfile and Credential (http://www.credreg.net/page/propertiesviewer#providesAdvancedStanding).

**Comment by siuc-nate** [comment]
Is "Credential B" the credential being described (with A being referenced) in both of those cases?

**Comment by stuartasutton** [comment]
I have also created an AdvancedStandingActions (http://www.credreg.net/page/propertiesviewer#AdvancedStandingAction).

**Comment by siuc-nate** [comment]
In other words, in a map like this, do I have the properties on the correct arrows?
![image](https://cloud.githubusercontent.com/assets/21346519/18209368/0ee31bc8-70f9-11e6-9868-830619d3497f.png)

**Comment by stuartasutton** [comment]
Correct.

**Comment by siuc-nate** [comment]
Regarding AdvancedStandingAction:
We do not currently have equivalent actions for requires/isRequiredFor/recommends/isRecommendedFor/renewal, as these are not (as far as I know) related to actions. If advanced standing is action-related, should it still be expressed via condition profile? Or is a more role-oriented approach (ie credential to credential direct role with an Action for conveying deeper information) preferred?

I am not sure I know of any other property aside from "targetCredential" within ConditionProfile that would be used by the advanced standing properties, unless a credential can provide advanced standing for an assessment or learning opportunity, or some similar relationship. Though saying that makes me wonder if the advanced standing is actually provided for a learning opportunity or some similar program that leads to a credential, rather than for the credential (as a standalone entity) itself.

**Comment by stuartasutton** [comment]
Nate, this discussion is going on in two issues--see also #48.

Nate, couple of things, I mis-stated in terms of your diagram. The diagram is functionally correct, but has different outcomes depending on which agent is making the assertions. This is hopefully made clear in issue #48.

Second, until such time as we see evidence (or someone tells us that it exists) that a credential provides advanced standing for an assessment or a learning opportunity, I think we should keep domain & range for the two properties as credential. If circumstances later dictate, we can add additional ranges.

Nate, I think we need to look at actions in a very pragmatic way. For me whether there is a credentialing action aligned with a property depends on whether there is a fairly high likelihood that binary property assertion will be subject to challenge and requests for verification. From what I gather from Bob's comments, agent claims that this credential or that one provide advanced standing for some other credential are subject to verification.  As you'll see over in #48, I propose the AdvancedStandingAction is used solely by 1st party agents stating that some 3rd party credential provides the foundation for advanced standing.

**Comment by stuartasutton** [comment]
I am closing this issue as complete--**BUT** am a bit uncomfortable with the conclusion of the discussion.

**Comment by stuartasutton** [comment]
At this time, we have the following properties and class:
> **ctdl: advancedStandingFor** (Credential 'A' says it provides advanced standing for Credential 'B)': domain=Credential; range=ConditionProfile and Credential sub-classes (see: http://www.credreg.net/page/propertiesviewer#advancedStandingFor);

> **ctdl:providesAdvancedStanding** (Credential 'B' says Credential 'A' provides advanced standing for it (Credential 'B')): domain=Credential; range=ConditionProfile and Credential subclasses (http://www.credreg.net/page/propertiesviewer#providesAdvancedStanding).

> **AdvancedStandingAction** (http://www.credreg.net/page/propertiesviewer#AdvancedStandingAction)

**Comment by stuartasutton** [comment]
As far as I can tell, there are three two possible questions:

 1. Is the range of the two advanced standing properties both Credential and ConditionProfile (use case 28 provides sufficient evidence for it to be ConditionProfile *at a minimum*); and

 2. Whether there should be a AdvancedStandingAction (need to be able to verify a claim by the agent providing the advanced standing seems sufficient to me to justify and action class).

**Comment by siuc-nate** [comment]
Would it help the definitions of the two properties to change the second one's use of A and B? e.g.:

ctdl:advancedStandingFor (Credential 'A' says it provides advanced standing for Credential 'B')
ctdl:providesAdvancedStanding (Credential 'A' says Credential 'B' provides advanced standing for it (Credential 'A'))
I think flipping them between definitions is what was throwing me off.  In the diagram of mine several posts up, "Credential A" would be the one in the middle in both cases (with Credential B being either on the left or right depending on which definition one was reading).

Regarding your questions:
1. Since a Credential could provide advanced standing for an assessment, learning opportunity (maybe a task?), or another credential, routing this through condition profile seems to make sense at first, but I wonder if there's anything else about condition profile (whose purpose is to group conditions together) that necessitates its use.  

For example, if a credential only provides advanced standing for another credential in the context of some other set of conditions (for example, only within a given region or only for a certain audience), then using a condition profile makes sense.  Otherwise, I think direct links are more correct (although that would extend the range of the properties to various other objects).

2. I'm not sure an action is any more necessary for this than it would be for any other assertion - would the logic that justifies an advanced standing action not also justify a "requires action" or "recommended for action" and so on? Maybe I'm misinterpreting what you mean.
