### ISSUE TITLE
Add educationalAlignment to AssessmentProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#52]
It makes sense that both of these could have a very direct relevance to competencies (via some kind of alignmentObject, most likely)

These objects are slowly becoming more and more alike.

**Comment by siuc-nate** [comment]
Actually, I just noticed that LearningOpportunityProfile has "educationalAlignment", so it probably doesn't need "targetCompetency".  I've updated the topic heading.

**Comment by stuartasutton** [comment]
Nate, I've thought more about this use of the generic "educationalAlignment" and IMO think it unwise. We are using AlignmentObject now to handle more than just competencies since EnumerationValue is not yet available. The only way it would be viable is to rely on **either** the explicit relations (e.g., targetCompetency pointing to an instance of AlignmentObject) **or** use AlignmentType's "alignmentType" property to identify the kind of alignment relationship.  I would think that acceptable only if we develop a small controlled vocabulary of alignment types: e.g.,
> occupation
> industry
> competency
> etc.
So the decisions is: 
1. Do we keep targetCompetency with a range of AlignmentObject; or
2. Do we use the generic "educationalAlignment" and the AlignmentObject's "alignmentType" property with accompanying vocabulary noted above.

**Comment by siuc-nate** [comment]
I would suggest using targetCompetency then, and employing it (instead of?) educationalAlignment on both AssessmentProfile and LearningOpportunityProfile.

**Comment by stuartasutton** [comment]
Agreed...
