### ISSUE TITLE
Extend the definition of availableOnlineAt to include a page or listing of location objects

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#60]
Case in point: http://www.credentialfinder.com/detail/credential/78

This credential is available at hundreds of potential locations.  Currently the only way we would be able to handle this is to have those locations copied into our own metadata (i.e. via hundreds of instances of profiles via the availableAt property).  It would be useful to have a property that can be used to point to some other resource (such as a webpage: http://www.msscusa.org/locations/ or something more machine-friendly) that does not necessarily indicate online availability (i.e., online courses), but does indicate an online resource that shows or lists physical locations.

My proposal is to extend the definition of availableOnlineAt to cover this use case.

**Comment by stuartasutton** [comment]
@siuc-nate & @jkitchensSIUC, I'll look at this closely. One thing we do not want to do (I don't think) is take ourselves down the labyrinthine "Offer" path (i.e., schema.org/Offer). What's on the other end of these 'locations' pointers is very much an offer; but, what I think is intended here is purely locational and not an invitation to describe the Offer on the other end. ***This Offer bit will likely come up because schema.or/CreativeWork has an "offers" property (pointing to Place).*** That said, Offer does have the property availableAtOrFrom that comes closer to what is being described here (if I am reading it correctly) but looses the original intent of an online focus. So, something in the line of  availableAtOrFrom and our availableOnlineAt... just thinking out loud.

**Comment by siuc-nate** [comment]
Actually, in thinking about this a little more, I wonder if it would be better to extend the range of availableAt to cover this, since availableAt is relevant for physical locations.

Then again, it is much easier to work with properties that only have one range associated with them - so your "availableAtOrFrom" could perhaps be explicitly used to indicate "an external resource that provides online and/or physical locations for the described resource" or something like that.

Would that work?

**Comment by stuartasutton** [comment]
OK, a ctdl:availabilityListing property sounds reasonable with a range of xsd:anyURI and a definition of: "An external resource that references online and/or physical locations for the described resource."

That would then give is:
 > ctdl:availableAt (physical place)
 > ctdl:availableOnlineAt (online place)
 > ctdl:avilabilityListing (listing of pysical and/or online places)

**Comment by stuartasutton** [comment]
***ACTION TAKEN:***

1. ctdl:avilabilityListing property added to spreadsheet with definition of "An external resource that lists online and/or physical locations for the described resource."
2. Property added to the classes: AssessmentProfile, Credential, LearningOpportunityProfile, & TaskProfile.
