### ISSUE TITLE
Condition Profile: replace credentialType with educationLevel or similar property

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#68]
In order to better indicate the intended purpose of the credentialType property of condition profile, we need to replace the property with "educationLevel" or some other similarly named property that points to an enumeration of postsecondary education levels (i.e., degree types).

There is no realistic situation in which having a non-specific, non-educational credential type would be a sensible requirement (e.g., no credential will realistically require that someone must have just "some" certification of any sort as a requirement, but plenty will require having a high school diploma).

**Comment by stuartasutton** [comment]
I've now enough domain experience to discuss whether you are correct, @siuc-nate . Perhaps @jkitchensSIUC  can pipe in. The credentialType property was added long, long ago and I seem to recall that it was put in at your request, @siuc-nate, because there was a perceived need to be able to say that a condition was a specific ***class of credential***.

**Comment by siuc-nate** [comment]
It's quite possible that I was the one who requested it at the time.  The thinking was that there would be a need to express a requirement (or recommendation, etc.) that someone must have a specific type of credential rather than a specific credential in order to attain some other credential.

At that time, credential type was still an enumeration; we had not changed it to be a set of subclasses.  So, we just used the entire credential type enumeration as the range for that property.  Recall that this led to several discussions when we tried to drop the credential type enumeration. 

Well, the more recent realization that came up in one of those discussions was that only the educational credential types would ever make sense as values for this property.  It is not logical to say that a credential may require "any" license or "any" certificate, but it's reasonable to think that one might require "any" high school diploma or "any" associate's degree.  (This also applies to other uses of condition profile - it doesn't make sense to assert that a credential will help prepare you for "any" license, but it might well help prepare you for "any" associate's degree)

Therefore, since one of our goals is to drop credential type as an enumeration and since the values within credential type are not entirely useful for this property, I think it makes sense to change the enumeration to an enumeration of education levels (specifically high school diploma and the degree types).  This, in turn, is (or was at the time of realization) roughly in line with the education level vocabulary, which means it probably makes sense to drop the credentialType property altogether in favor of an educationLevel property that better serves the original intent and purpose of the credentialType property in this profile.

However, if educationLevel is to be more than a listing of specific types of educational credentials, perhaps a standalone vocabulary is needed.  I'm certainly open to suggestions on all of this.

**Comment by mparsons1953** [comment]
We need need to rename audienceLevel with educationLevel, and update the vocabulary to match the previously discussed and agreed upon list.

- High School or Equivalent
- Associate
- Bachelor
- Master
- Doctoral

**Comment by siuc-nate** [comment]
We have updated the vocabularies spreadsheet to rename AudienceLevel to EducationLevel, but we need to double-check other spreadsheets for references to "AudienceLevel" to ensure everything is aligned.

**Comment by stuartasutton** [comment]
I note that there are no definitions for these concepts in the vocabulary spreadsheet. As soon as there are definitions, I'll update skos schema GitHub.

**Comment by stuartasutton** [comment]
ACTIONS TAKEN:

1. OK, as for the addition of ctdl:educationLevel, we need  a definition. I am adding: "A point in a progression through an educational or training context, for which the described resource is intended." And, I am adding an owl:equivalentProperty to dct:educationLevel.
2. I removed the ctdl:credentialType property from ctdl:ConditionProfile.
3. While you consider the ctdl:credentialType (range of subclass of ctdl:Credential) incorrect on ctdl:ConditionProfile, the property does have utility otherwise; so I ask that it ***not*** be dropped from CTDL. For example, Erik Korb is already using the ctdl:credentialType property in verifiable claims. Instead I am simply adding cdtl:educationLevel and switching it out for cdtl:credentialType in ctdl:ConditionProfile.
