### ISSUE TITLE
Learning Opportunity Profile: "assessmentProfile" and "hasAssessment"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#70]
The LearningOpportunityProfile currently has both "assessmentProfile" and "hasAssessment" properties.  Should one of these be dropped?

**Comment by stuartasutton** [comment]
I suggest instead that we drop AssessmentProfile from the range of hasAssessment resulting in the property only pointing to an actual instance of the Assessment class. If the intention with assessments is that there is always an intermediate AssessmentProfile node and one never points directly to an assessment, then hasAssessment should be removed.

**Comment by siuc-nate** [comment]
It's more a question of whether or not we want to imply that someone describing a learning opportunity must list out every single assessment within that learning opportunity (i.e., all of the tests, quizzes, etc.). My understanding was that the intent of AssessmentProfile was for standalone assessments not directly affiliated with a learning opportunity.

This could also be confusing to users since it will not always be clear whether they should attach an assessment to a learning opportunity or to the requirements that that learning opportunity is referenced by (or perhaps both).  There's a lot of opportunity for inconsistencies that I would like to avoid.

**Comment by stuartasutton** [comment]
Nate, there is nothing at the level of the CTDL that says there are any "have to's". The presence of the two properties do nothing more than make it possible for a LearningOpportunityProfile to point *either* to an AssessmentProfile or to an instance of (or set of) Assessment.

**Comment by siuc-nate** [comment]
Yes, but I think that possibility is potentially confusing - if you are someone entering data (or marking up a webpage, or designing a system that converts your database into CTDL JSON, etc), and you are tasked with figuring out where to describe a set of requirements that include a learning opportunity and an assessment, it would not be obvious whether you should include that assessment as a part of that learning opportunity or as a part of the requirements directly.  

It would also imply that you are supposed to include data about all of your learning opportunity's assessments (tests, quizzes, etc. - even if you don't "have to"), which is not the intent of those properties under learning opportunity (unless I am mistaken).

I guess I'm not sure what the use case for including those properties as a part of learning opportunity is.

**Comment by stuartasutton** [comment]
Please review and approve this set of resolutions. One is a significant change: 
 1. Drop AssessmentProfile from the range of hasAssessment so that we do not get recursive AssessmentProfile instances using hasAssessment that point to another AssessmentProfile (http://www.credreg.net/page/propertiesviewer#hasAssessment);
 2. Added new language to the definition of AssessmentProfile to align it with what Nate has been assuming--that the profile only applies to stand-alone assessments; and, that as assessment that is part of a learning opportunity would be described in the context of the relevant LearningOpportunityProfile (http://www.credreg.net/page/propertiesviewer#AssessmentProfile).
 3. I did not remove either "assessmentProfiled" and "hasAssessment" from the range of LearningOpportunityProfile because such a profile might point directly to an assessment or to the profiling description of an assessment where that assessment must be annotated. Potential confusion in use should not be solved by eliminating either, but rather in making the use/choices explicit (@@@).
 4. I changes the name of ctdl:hasAssessment to ctdl:targetAssessment (http://www.credreg.net/page/propertiesviewer#targetAssessment).

@jkitchensSIUC, the change no. 2 above is a significant change and I'd like a final verdict from you. "Assumptions" about use of a class or property that have not been explicitly stated are ***not*** good--I've tried to make the assumption in no. 2 clear--but is the assumption shared that AssessmentProfile is for stand-alone assessments and not for assessments associated with a learning opportunity? Please verify.

**Comment by siuc-nate** [comment]
1, 2, and 4 sound good to me.

3 I'm still a little bit confused on - are you saying a learning opportunity can still point to an assessment profile and to an assessment (presumably via URL) directly?  It would seem that making the change in item 2 but not applying it to item 3 might be confusing...or am I missing what you mean about the change in item 2?

**Comment by stuartasutton** [comment]
Combinations enabled:

Credential==>ConditionProfile==>Assessment
Credential==>ConditionProfile==>AssessmentProfile==>Assessment
Credential==>ConditionProfile==>LearningOpportunityProfile==>Assessment
Credential==>ConditionProfile==>LearningOpportunityProfile==>AssessmentProfile==>Assessment

**Comment by mparsons1953** [comment]
We have reviewed, and agree that any changes should be made to accommodate the combinations described.

**Comment by stuartasutton** [comment]
I'll make any necessary changes to the spreadsheet. There are not many.

**Comment by stuartasutton** [comment]
COMBINATIONS VERIFIED - Closing issue
