### ISSUE TITLE
CredentialAlignmentObject: add "name" property

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#74]
We currently list these related properties:
- description
- targetName
- targetDescription
- targetUrl

We should probably include the "name" property to go along with the "description" property (and possibly a "url" property?  I'm not sure this would ever be used).

**Comment by stuartasutton** [comment]
Not sure I understand the "name" addition. It says that the AlignmentObject itself has a name. Same with addition of "url"...that basically says that AlignmentObject is not a bnode but a non-literal (i.e., a resource identified by URI). Without some recognized need to reference instances of AlignmentObject outside the graph where they are defined, I see no need to add an a "url" property.

**Comment by siuc-nate** [comment]
To clarify, we explicitly include "description" in our metadata for this (even though it inherits it from schema:Thing) but we don't explicitly include name or url (which it also inherits).

The use case is one where a competency needs to be entered, but it does not have a framework or a URL of its own, thus the alignmentObject becomes the actual source of the data rather than just a pointer to it, thus "name" and "description" would be used rather than "targetName" and "targetDescription" (If I'm understanding the intent of those properties correctly).  I'm still not sure about URL/targetURL.

**Comment by stuartasutton** [comment]
Using your example of a competency from a framework that hasn't been identified, you'd nevertheless use targetDescription for the text of the competency; and , if they had somehow identified the competency by name, you'd use targetName. Since your example competency has no embodiment in a formal scheme, there would probably be no educationalFramework identified. For that same reason, it is unlikely that you have a targetUrl that identifies the competency described with targetDescription. 

There is no need for name and description from Thing.

**Comment by siuc-nate** [comment]
Then in that case, should we remove the explicit "description" property?

**Comment by stuartasutton** [comment]
It wouldn't hurt and would certainly stop and unnecessary wonder about
where to put a description.

**Comment by stuartasutton** [comment]
I have deleted ctdl:description from CredentialAlignmentObject.
