### ISSUE TITLE
Condition Profile: weight range/scale

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#82]
Is the weight property of condition profile intended to be considered as a percentage value (e.g., 0.1 - 1.0 = 1% - 100%) and thus have a maximum value of 1.0? Or is it intended to be used some other way?

**Comment by stuartasutton** [comment]
We need a metric...just so it is meaningful and clear and can be validated as a datatype.

**Comment by siuc-nate** [comment]
In another project, we used a rating scale for standards alignments based loosely on the EQuIP Rubrics:
http://www.achieve.org/our-initiatives/equip/rubrics-and-feedback-forms

Namely a four-step scale along the lines of:
- exemplary
- strong
- weak
- poor
(and potentially a fifth, "not applicable")

These would probably be more meaningful to a consumer than an arbitrary number with an undefined scale - but I would want feedback from the rest of the team.

**Comment by siuc-nate** [comment]
Alternatively, could a scale be prescribed in the description?

**Comment by stuartasutton** [comment]
It depends on what kind of data you want. Nothing wrong with the four steps
if you don't want more fine-grained, continuous scale. Then his should be
handled than as a declared controlled vocabulary (WeightScale). Perhaps one
that is loosely defined so that it is able to express that *something* is
exemplary, or *something* is weak...and might be otherwise useful.

"Not applicable" makes no sense in an assertional language like the CTDL.
If weight isn't applicable in the context of the resource being described
-- i.e., there is no assertion/statement to be made, then the property
simply doesn't appear in the data.

**Comment by stuartasutton** [comment]
Nate, when you say, "can a scale be defined in a definition", do you mean list the terms in the definition and treat the property as a literal? I.e., a text entry field as opposed to a select (from vocabulary)? I wouldn't recommend it if the the field is deemed important at all. No matter what you list out in the definition, if you leave room for them to type in crap, crap is what you'll get. A select from actually limits the values.

Also, while there is nothing technically objectionable about the four concepts, they signal a sense of quality or value where a light weight is not necessary a bad (poor) thing. The use of percentages or some other value denotes nothing more than 'weight' given. It;s up to application to determine whether they want to translate those weights into value judgments.

**Comment by siuc-nate** [comment]
What I meant with my comment about the scale was, could the definition say something along the lines of "A weight assigned between 0 and 1 that indicates the strength(?) of the assertion, with 0 being weakest and 1 being strongest"

Basically, defining the scale by defining the minimum and maximum values along with what those values correspond to.

**Comment by stuartasutton** [comment]
Yup, that makes sense.

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

Revised: http://www.credreg.net/page/propertiesviewer#weight

1. Note that the definition has been adjusted to make the property useful in any comparison or mapping situation; and
2. Slight revision of Nate's language in usage note with the addition of the phrase "decimal value" weight" instead of just "weight" to avoid entry of fractions (1/2, 1/4).
